# Generated by Django 4.2.16 on 2024-09-28 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('market_role', models.CharField(choices=[('Importer', 'Importer'), ('Exporter', 'Exporter'), ('Both', 'Both')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LNGVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('volume', models.FloatField(verbose_name='In 10^6 m^3 (liquid)')),
                ('direction', models.CharField(choices=[('Import', 'Import'), ('Export', 'Export')], max_length=100)),
                ('market_share', models.FloatField(verbose_name='In %')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lng_volumes.country')),
            ],
        ),
    ]
