# Generated by Django 4.2.16 on 2024-09-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lng_volumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lngvolume',
            name='market_share',
            field=models.FloatField(verbose_name='Market Share In %'),
        ),
        migrations.AlterField(
            model_name='lngvolume',
            name='volume',
            field=models.FloatField(verbose_name='Volume (x 10^6 cubic meters of liquid)'),
        ),
    ]
